// League team data — rosters and stats sourced from the team pages of this repo.
// Attribute scale 1–10: sp = Speed, ag = Agility, st = Strength, to = Toughness.
const TEAMS = [
  {
    id: 'halfling',
    race: 'Halflings',
    name: 'Norwich Town',
    tagline: 'of Northfolkshire',
    color: '#3d9e45', color2: '#8bd27f',
    img: '../Images/halfling_team.jpg',
    lore: 'Underdogs who rely on agility, surprise plays and a Treeman to provide the muscle.',
    roster: [
      { name: 'Perry Picklewick', role: 'Forward Scout', sp: 8, ag: 5, st: 2, to: 4 },
      { name: 'Tilly Thistledown', role: 'Forward Scout', sp: 8, ag: 5, st: 2, to: 4 },
      { name: 'Bramble Burrows', role: 'Heavy Hitter', sp: 5, ag: 3, st: 4, to: 6 },
      { name: 'Grum Gruffle', role: 'Heavy Hitter', sp: 5, ag: 3, st: 4, to: 6 },
      { name: 'Wick Willoughby', role: 'Ball Handler', sp: 6, ag: 5, st: 2, to: 4 },
      { name: 'Nettle Nimblepie', role: 'Ball Handler', sp: 6, ag: 5, st: 2, to: 4 },
      { name: 'Sage Sixmeals', role: 'Support Squad', sp: 6, ag: 4, st: 3, to: 5 },
      { name: 'Odo Overhill', role: 'Support Squad', sp: 6, ag: 4, st: 3, to: 5 },
      { name: 'Pip Puddifoot', role: 'Forward Scout', sp: 8, ag: 4, st: 2, to: 4 },
      { name: 'Marlo Mudbottom', role: 'Support Squad', sp: 6, ag: 4, st: 3, to: 5 },
      { name: 'Fern Foxglove', role: 'Ball Handler', sp: 7, ag: 5, st: 2, to: 4 },
      { name: 'Grootbranch the Ancient', role: 'Treeman', sp: 2, ag: 1, st: 6, to: 10 },
    ],
  },
  {
    id: 'woodelf',
    race: 'Wood Elves',
    name: 'The Floating Oaks',
    tagline: 'grace and ferocity combined',
    color: '#2e8b74', color2: '#9fe0c4',
    img: '../Images/wood_elf_team.webp',
    lore: 'Exceptional speed, agility and ball-handling — fragile, but nearly impossible to pin down.',
    roster: [
      { name: 'Thalan Underbow', role: 'Thrower', sp: 7, ag: 4, st: 3, to: 7 },
      { name: 'Finrod Leafwalker', role: 'Catcher', sp: 8, ag: 4, st: 2, to: 7 },
      { name: 'Aerol Swiftfoot', role: 'Catcher', sp: 8, ag: 4, st: 2, to: 7 },
      { name: 'Galion Greenstride', role: 'Wardancer', sp: 8, ag: 4, st: 3, to: 7 },
      { name: 'Cirdan Skyrunner', role: 'Wardancer', sp: 8, ag: 4, st: 3, to: 7 },
      { name: 'Tauriel Quickbark', role: 'Lineman', sp: 7, ag: 4, st: 3, to: 7 },
      { name: 'Legolin Arrowshot', role: 'Lineman', sp: 7, ag: 4, st: 3, to: 7 },
      { name: 'Elrohir Starlight', role: 'Lineman', sp: 7, ag: 4, st: 3, to: 7 },
      { name: 'Haldir Leafshade', role: 'Lineman', sp: 7, ag: 4, st: 3, to: 7 },
      { name: 'Gildor Inglorion', role: 'Lineman', sp: 7, ag: 4, st: 3, to: 7 },
      { name: 'Beleg Strongbow', role: 'Lineman', sp: 7, ag: 4, st: 3, to: 7 },
      { name: 'Celeborn the Wise', role: 'Treeman', sp: 2, ag: 1, st: 6, to: 10 },
    ],
  },
  {
    id: 'human',
    race: 'Humans',
    name: 'Arsenal',
    tagline: 'balance in all things',
    color: '#b03a3a', color2: '#e8c15a',
    img: '../Images/Dalle4_human_field.webp',
    lore: 'A balanced amalgamation of agility, strength and dependability — adaptable to any scenario.',
    roster: [
      { name: 'Alric the Accurate', role: 'Thrower', sp: 6, ag: 3, st: 3, to: 8 },
      { name: 'Berin Fastfoot', role: 'Catcher', sp: 8, ag: 4, st: 2, to: 7 },
      { name: 'Gorin Stoutarm', role: 'Blitzer', sp: 7, ag: 3, st: 3, to: 8 },
      { name: 'Helfdan the Swift', role: 'Catcher', sp: 8, ag: 4, st: 2, to: 7 },
      { name: 'Olaf Hammerfist', role: 'Blitzer', sp: 7, ag: 3, st: 3, to: 8 },
      { name: 'Sigurd Strongarm', role: 'Lineman', sp: 6, ag: 3, st: 3, to: 8 },
      { name: 'Erik Ironshield', role: 'Lineman', sp: 6, ag: 3, st: 3, to: 8 },
      { name: 'Lars the Leader', role: 'Lineman', sp: 6, ag: 3, st: 3, to: 8 },
      { name: 'Ragnar the Rock', role: 'Ogre', sp: 5, ag: 2, st: 5, to: 9 },
      { name: 'Thorvald Thunder', role: 'Lineman', sp: 6, ag: 3, st: 3, to: 8 },
      { name: 'Bjorn Bearclaw', role: 'Blitzer', sp: 7, ag: 3, st: 3, to: 8 },
      { name: 'Wilhelm Windrunner', role: 'Catcher', sp: 8, ag: 4, st: 2, to: 7 },
    ],
  },
  {
    id: 'orc',
    race: 'Orcs',
    name: 'The Skull Crushers',
    tagline: 'control the line, crush the rest',
    color: '#4a6b2a', color2: '#c9a227',
    img: '../Images/orc_team.webp',
    lore: 'Brute strength on the line of scrimmage, with sneaky goblin agility for dynamic maneuvers.',
    roster: [
      { name: 'Grot Snaggle', role: 'Lineman', sp: 5, ag: 3, st: 3, to: 9 },
      { name: 'Uzgob Smashgit', role: 'Black Orc', sp: 4, ag: 2, st: 4, to: 9 },
      { name: 'Grimgor Gouger', role: 'Blitzer', sp: 6, ag: 3, st: 3, to: 8 },
      { name: 'Skarfang Skuller', role: 'Thrower', sp: 5, ag: 3, st: 3, to: 8 },
      { name: 'Wazzbad Powkick', role: 'Blitzer', sp: 6, ag: 3, st: 3, to: 8 },
      { name: 'Nobbla Stomper', role: 'Lineman', sp: 5, ag: 3, st: 3, to: 9 },
      { name: 'Zogoth the Mean', role: 'Black Orc', sp: 4, ag: 2, st: 4, to: 9 },
      { name: 'Grod Badthrow', role: 'Thrower', sp: 5, ag: 3, st: 3, to: 8 },
      { name: 'Muzgash Maimer', role: 'Blitzer', sp: 6, ag: 3, st: 3, to: 8 },
      { name: 'Gashnak Breaker', role: 'Black Orc', sp: 4, ag: 2, st: 4, to: 9 },
      { name: 'Snikrot Sneaky', role: 'Goblin', sp: 6, ag: 3, st: 2, to: 7 },
      { name: 'Badruk Bashface', role: 'Blitzer', sp: 6, ag: 3, st: 3, to: 8 },
    ],
  },
  {
    id: 'undead',
    race: 'Undead',
    name: 'Chariots of Death',
    tagline: 'relentless, regenerating, remorseless',
    color: '#5b4a8a', color2: '#a7f070',
    img: '../Images/undead_team.webp',
    lore: 'Zombies, ghouls, skeletons, wights and mummies — attrition warfare with eerie speed.',
    roster: [
      { name: 'Gravewalker', role: 'Zombie', sp: 4, ag: 2, st: 3, to: 8 },
      { name: 'Bonecruncher', role: 'Mummy', sp: 3, ag: 1, st: 5, to: 9 },
      { name: 'Shadowswift', role: 'Wight', sp: 6, ag: 3, st: 3, to: 8 },
      { name: 'Ghoulcatcher', role: 'Ghoul', sp: 7, ag: 3, st: 3, to: 7 },
      { name: 'Nightshroud', role: 'Wight', sp: 6, ag: 3, st: 3, to: 8 },
      { name: 'Tombdancer', role: 'Skeleton', sp: 5, ag: 2, st: 3, to: 7 },
      { name: 'Screamweaver', role: 'Ghoul', sp: 7, ag: 3, st: 3, to: 7 },
      { name: 'Deadweight', role: 'Zombie', sp: 4, ag: 2, st: 3, to: 8 },
      { name: 'Skullflinger', role: 'Skeleton', sp: 5, ag: 2, st: 3, to: 7 },
      { name: 'Darkwhisper', role: 'Ghoul', sp: 7, ag: 3, st: 3, to: 7 },
      { name: 'Cryptkeeper', role: 'Mummy', sp: 3, ag: 1, st: 5, to: 9 },
      { name: 'Soulreaper', role: 'Wight', sp: 6, ag: 3, st: 3, to: 8 },
    ],
  },
  {
    id: 'dwarf',
    race: 'Dwarves',
    name: 'The Dwarf Smashers',
    tagline: 'forged in Karak Kazril',
    color: '#8a5a2a', color2: '#e0912e',
    img: '../Stadiums/IMG_6834.WEBP',
    lore: 'Resilience, strength and tactical brilliance from the Forge of Glory, led by Borin Ironbeard.',
    roster: [
      { name: 'Borin Ironbeard', role: 'White Dwarf', sp: 5, ag: 3, st: 4, to: 9 },
      { name: 'Grudgecrusher', role: 'Steam Roller', sp: 3, ag: 1, st: 6, to: 10 },
      { name: 'Thrain Stonefoot', role: 'Blocker', sp: 4, ag: 2, st: 4, to: 9 },
      { name: 'Kargan Ironfist', role: 'Runner', sp: 6, ag: 3, st: 3, to: 8 },
      { name: 'Durin Thundershield', role: 'Blitzer', sp: 5, ag: 3, st: 4, to: 8 },
      { name: 'Snorri Anvilsson', role: 'Blocker', sp: 4, ag: 2, st: 4, to: 9 },
      { name: 'Gromli Firebrow', role: 'Blocker', sp: 4, ag: 2, st: 4, to: 9 },
      { name: 'Balin Oathkeeper', role: 'Lineman', sp: 4, ag: 2, st: 3, to: 9 },
      { name: 'Dwalin Rockjaw', role: 'Lineman', sp: 4, ag: 2, st: 3, to: 9 },
      { name: 'Nori Grudgeborn', role: 'Runner', sp: 6, ag: 3, st: 3, to: 8 },
      { name: 'Thorek Hammerhand', role: 'Blitzer', sp: 5, ag: 3, st: 4, to: 8 },
      { name: 'Okri Stoutale', role: 'Lineman', sp: 4, ag: 2, st: 3, to: 9 },
    ],
  },
  {
    id: 'goblin',
    race: 'Goblins',
    name: 'MadTown Green Goobers',
    tagline: 'chaos is a ladder (with springs)',
    color: '#5a8a2a', color2: '#d6e34a',
    img: '../Stadiums/IMG_6836.WEBP',
    lore: 'Unpredictable misfits from the Chaos Pit — bombers, squigs, chainsaw fanatics and sneaky tricks.',
    roster: [
      { name: 'Grimgor Gutstabber', role: 'Goblin King', sp: 6, ag: 4, st: 3, to: 6 },
      { name: 'Loony "Chainsaw" Gitz', role: 'Fanatic', sp: 5, ag: 2, st: 5, to: 6 },
      { name: '"Skyrocket" Snot', role: 'Doom Diver', sp: 9, ag: 4, st: 2, to: 5 },
      { name: 'Bogrot da Borrowed', role: 'Black Orc', sp: 4, ag: 2, st: 4, to: 9 },
      { name: 'Snig Squigbiter', role: 'Squig Herder', sp: 7, ag: 4, st: 2, to: 5 },
      { name: 'Wurzag Bombchukka', role: 'Bomber', sp: 6, ag: 3, st: 2, to: 5 },
      { name: 'Nibbla Kneecapper', role: 'Sneak', sp: 7, ag: 4, st: 2, to: 5 },
      { name: 'Gitface Grinna', role: 'Sneak', sp: 7, ag: 4, st: 2, to: 5 },
      { name: 'Zoggin Earchewer', role: 'Lineman', sp: 6, ag: 3, st: 2, to: 5 },
      { name: 'Skabrat Pusboil', role: 'Lineman', sp: 6, ag: 3, st: 2, to: 5 },
      { name: 'Grubnash Toefungus', role: 'Lineman', sp: 6, ag: 3, st: 2, to: 5 },
      { name: 'Mork da Lucky', role: 'Lineman', sp: 6, ag: 4, st: 2, to: 5 },
    ],
  },
  {
    id: 'viking',
    race: 'Vikings',
    name: 'The Frostheim Raiders',
    tagline: 'fury of the north',
    color: '#3a6ea5', color2: '#cfe8ff',
    img: '../Stadiums/IMG_6838.WEBP',
    lore: 'Forged in the ice of Norsca and led from the Frozen Fortress — they never back down.',
    roster: [
      { name: 'Balder Iceblood', role: 'Ulfwerenar (Captain)', sp: 6, ag: 3, st: 5, to: 8 },
      { name: 'Thorin Stormbringer', role: 'Ulfwerenar', sp: 6, ag: 3, st: 5, to: 8 },
      { name: 'Ragnar Frostheart', role: 'Berserker', sp: 6, ag: 4, st: 4, to: 8 },
      { name: 'Loki Shadowstep', role: 'Berserker', sp: 6, ag: 4, st: 4, to: 8 },
      { name: 'Bjorn Ironhide', role: 'Lineman', sp: 6, ag: 4, st: 3, to: 7 },
      { name: 'Erik Thunderfist', role: 'Lineman', sp: 6, ag: 4, st: 3, to: 7 },
      { name: 'Olaf the Brave', role: 'Lineman', sp: 6, ag: 4, st: 3, to: 7 },
      { name: 'Kjell Winterborn', role: 'Lineman', sp: 6, ag: 4, st: 3, to: 7 },
      { name: 'Sigurd Frostwolf', role: 'Runner', sp: 7, ag: 4, st: 3, to: 7 },
      { name: 'Einar the Swift', role: 'Runner', sp: 7, ag: 4, st: 3, to: 7 },
      { name: 'Freya Shieldmaiden', role: 'Thrower', sp: 6, ag: 4, st: 3, to: 7 },
      { name: 'Fenrir the Winter Wolf', role: 'Snow Troll', sp: 4, ag: 1, st: 6, to: 9 },
    ],
  },
];
